Разметка всех страниц
htmlacademy-htmlcss/2329637-sedona-1 pull request #4
Opened 2023-08-18 06:22 UTC by BloodhoundG

---
:mortar_board: [Разметка всех страниц](https://up.htmlacademy.ru/htmlcss-individual/1/user/2329637/tasks/4)

:boom: https://htmlacademy-htmlcss.github.io/2329637-sedona-1/4/

2023-08-18 17:48 UTC, NikolaiKotikov requested changes

2023-08-18 17:48 UTC, NikolaiKotikov commented on index.html
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
Это не нужно, убрать

2023-08-18 17:48 UTC, NikolaiKotikov commented on index.html
> +        <a href="#"><img class="logo" src="#" alt="Логотип Седона" /></a>
На будущее, заменить на svg

2023-08-18 17:48 UTC, NikolaiKotikov commented on index.html
> +              <img src="#" alt="Иконка лупы" />
Заменить на  svg (Все комменты про графику сейчас править не нужно)

2023-08-18 17:48 UTC, NikolaiKotikov commented on index.html
> +              <img src="#" alt="Иконка сердца" />
Заменить на svg
Добавить элемент для счетчика избранного

2023-08-18 17:48 UTC, NikolaiKotikov commented on index.html
> +      <h1 class="visual-hidden">Седона - небольшой городок в Аризоне</h1>
.visually-hidden
.sr-only

2023-08-18 17:48 UTC, NikolaiKotikov commented on index.html
> +        <ul class="navigation-user">
Вынести из nav

2023-08-18 17:48 UTC, NikolaiKotikov commented on index.html
> +        <table class="advantages-table" border="1">
Убрать таблицу, сверстать обычными дивами

2023-08-18 17:48 UTC, NikolaiKotikov commented on index.html
> +              <hr />
Все hr убрать

2023-08-18 17:48 UTC, NikolaiKotikov commented on index.html
> +            <img src="#" alt="Иконка фастфуда" />
будет  svg

2023-08-18 17:48 UTC, NikolaiKotikov commented on index.html
> +        <a class="button uppercase" href="catalog.html">
Кнопка

2023-08-18 17:48 UTC, NikolaiKotikov commented on index.html
> +              <img src="#" alt="Логотип Вконтакте" />
Все лого  в свг

2023-08-18 17:48 UTC, NikolaiKotikov commented on index.html
> +        <span class="telephone">+7 (812) 812-12-12</span>
Ссылка href="tel:+78128121212"

2023-08-18 17:48 UTC, NikolaiKotikov commented on index.html
> +            <a class="social-link" href="https://t.me/htmlacademy">
target="_blank" нужен для того, чтобы ссылка открылась в новой вкладке, а не в текущей 

Для всех ссылок соц сетей

2023-08-18 17:48 UTC, NikolaiKotikov commented on catalog.html
> +        <form action="#" method="get">
method="POST"

2023-08-18 17:48 UTC, NikolaiKotikov commented on catalog.html
> +            <button class="button" type="button">Применить</button>
type="submit"

2023-08-18 17:48 UTC, NikolaiKotikov commented on catalog.html
> +        <a href="#" class="button">
Кнопки для смены отображения (Плитка, список)

2023-08-18 17:48 UTC, NikolaiKotikov commented on catalog.html
> +        <hr />
убрать

2023-08-18 17:48 UTC, NikolaiKotikov commented on catalog.html
> +          </li>
заменить на li с точками
```html
<li>
<span>...</span>
</li>
```

2023-08-20 09:53 UTC, BloodhoundG commented on index.html
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
Убрал    
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />

2023-08-20 09:53 UTC, BloodhoundG commented on index.html
> +        <ul class="navigation-user">
Вынес

2023-08-20 09:53 UTC, BloodhoundG commented on index.html
> +              <img src="#" alt="Иконка сердца" />
Добавил

2023-08-20 09:53 UTC, BloodhoundG commented on index.html
> +      <h1 class="visual-hidden">Седона - небольшой городок в Аризоне</h1>
Заменил

2023-08-20 09:53 UTC, BloodhoundG commented on index.html
> +              <hr />
убрал

2023-08-20 09:53 UTC, BloodhoundG commented on index.html
> +        <table class="advantages-table" border="1">
сверстал, но есть вопросы

2023-08-20 09:53 UTC, BloodhoundG commented on index.html
> +        <a class="button uppercase" href="catalog.html">
изменил на кнопку

2023-08-20 09:53 UTC, BloodhoundG commented on index.html
> +            <a class="social-link" href="https://t.me/htmlacademy">
Атрибут добавлен во все ссылки на соц сети

2023-08-20 09:53 UTC, BloodhoundG commented on index.html
> +        <span class="telephone">+7 (812) 812-12-12</span>
номер сделан ссылкой

2023-08-20 09:53 UTC, BloodhoundG commented on catalog.html
> +        <form action="#" method="get">
метод POST установлен

2023-08-20 09:53 UTC, BloodhoundG commented on catalog.html
> +            <button class="button" type="button">Применить</button>
изменён на Submit

2023-08-20 09:53 UTC, BloodhoundG commented on catalog.html
> +        <a href="#" class="button">
добавлены кнопки

2023-08-20 09:53 UTC, BloodhoundG commented on catalog.html
> +        <hr />
Убрано

2023-08-20 09:53 UTC, BloodhoundG commented on catalog.html
> +          </li>
Заменил

2023-08-20 18:25 UTC, merged